source:
  repo: https://github.com/smsilva/argocd.git
  targetRevision: wasp
  path: charts/common

destination:
  cluster: in-cluster

applications:
  - name: kustomize
    namespace: default
    wave: 0

  - name: external-secrets
    namespace: default
    wave: 1

  - name: wasp-base
    namespace: default
    wave: 1

  - name: crossplane-base
    namespace: crossplane-system
    wave: 2

  # - name: crossplane-providers
  #   namespace: crossplane-system
  #   wave: 2
