source:
  repo: https://github.com/smsilva/argocd.git
  targetRevision: wasp
  path: charts/common

destination:
  cluster: in-cluster

applications:
  # - name: kustomize
  #   namespace: default
  #   wave: 0

  - name: wasp-base
    namespace: default
    wave: 1

  - name: crossplane-providers
    namespace: crossplane
    wave: 2

  - name: crossplane-config
    namespace: crossplane
    wave: 3

  # - name: wasp-secrets
  #   namespace: default
  #   wave: 4
