---
apiVersion: mongodbatlas.silvios.me/v1alpha1
kind: Team
metadata:
  name: atlas-team-example
  namespace: default
spec:
  organizationId: 61c9c79454722979b41e355d
  team: 
    name: "Atlas_Team_Example"
    users:
      - foo@bar.com
