apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: default
    name: in-cluster
  source:
    repoURL: git@github.com:smsilva/argocd.git
    targetRevision: wasp
    path: charts/undercloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
