---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: httpbin-pre-sync
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
        - name: initialization
          image: alpine:latest
          command: ["sleep", "5"]
      restartPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
      annotations:
        argocd.argoproj.io/sync-wave: "3"
    spec:
      serviceAccountName: httpbin
      containers:
      - name: httpbin
        image: docker.io/kennethreitz/httpbin:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: httpbin-sync
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "4"
spec:
  template:
    spec:
      containers:
        - name: finishing-sync
          image: alpine:latest
          command: ["sleep", "5"]
      restartPolicy: Never
