apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: clusters.kubernetes.silvios.me
spec:
  compositeTypeRef:
    apiVersion: kubernetes.silvios.me/v1alpha1
    kind: Cluster
  resources:
    - base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: terraform.silvios.me/v1alpha1
              kind: StackInstance
              metadata:
                name: wasp-undercloud
                namespace: default
              spec:
                stack:
                  provider: azurerm
                  backend: azurerm
                  registry: docker.io
                  image: silviosilva/azure-undercloud-cluster
                  version: 0.3.0
                vars:
                  cluster_name: wasp-undercloud
                  cluster_location: eastus2
                  cluster_version: "1.21.2"
                outputs:
                  - aks_id
                  - aks_kubelet_identity_client_id
                  - kubeconfig

      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.manifest.metadata.name
          transforms:
            - type: string
              string:
                fmt: "azure-k8s-cluster-%s"

    - base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: game-demo
                namespace: default
              data:
                player_initial_lives: "3"
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.manifest.metadata.name
          transforms:
            - type: string
              string:
                fmt: "azure-k8s-cluster-%s"

        - fromFieldPath: metadata.uid
          toFieldPath: spec.forProvider.manifest.data.myuuid
      readinessChecks:
        - type: None
