apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-operator
spec:
  profile: default
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          podAnnotations:
            argocd.argoproj.io/sync-wave: "1"
    egressGateways:
      - name: istio-egressgateway
        enabled: false
  values:
    global:
      proxy:
        autoInject: enabled
        privileged: false
    gateways:
      istio-ingressgateway:
        serviceAnnotations:
          service.beta.kubernetes.io/azure-dns-label-name: silvios-dev
