apiVersion: v1
appVersion: 0.1.6
description: A Helm chart for the New Relic Pixie integration.
home: https://hub.docker.com/u/newrelic
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
keywords:
- newrelic
- pixie
- monitoring
maintainers:
- name: douglascamata
name: newrelic-pixie
sources:
- https://github.com/newrelic/
version: 0.1.0-alpha.7
