source:
  repo: https://github.com/smsilva/argocd.git
  targetRevision: wasp
  path: charts/common

destination:
  cluster: in-cluster

applications:
  - name: terraform-controller
    namespace: default
    wave: 0

  - name: external-secrets
    namespace: default
    wave: 0

  - name: kustomize
    namespace: default
    wave: 1

  - name: wasp-base
    namespace: default
    wave: 1

  # - name: wasp-buckets
  #   namespace: default

  - name: wasp-clusters
    namespace: default
