{{- range $instance := .Values.instances }}
---
apiVersion: terraform.silvios.me/v1alpha1
kind: StackInstance
metadata:
  name: {{ $instance.name }}
spec:
  stack:
    provider: google
    backend: gcs
    registry: docker.io
    image: silviosilva/google-bucket
    version: edge
  vars:
    name: {{ $instance.name }}
    location: {{ $instance.location }}
  outputs:
    - id
    - self_link
    - url
    - project
{{- end }}
