apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: azurerm-credentials
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: SecretStore
    name: azurerm

  target:
    name: azurerm-credentials-1
    creationPolicy: Owner

  data:
  - secretKey: ARM_ACCESS_KEY
    remoteRef:
      key: secret/arm-access-key-terraform
