apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: docker-hub
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: SecretStore
    name: azurerm

  target:
    name: docker-hub
    creationPolicy: Owner

  data:
  - secretKey: username
    remoteRef:
      key: secret/docker-hub-username

  - secretKey: password
    remoteRef:
      key: secret/docker-hub-password
