apiVersion: v1
appVersion: 1.5.0
description: A Helm chart to deploy the New Relic Kube Events
home: https://docs.newrelic.com/docs/integrations/kubernetes-integration/kubernetes-events/install-kubernetes-events-integration
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
keywords:
- events
- newrelic
- monitoring
maintainers:
- name: douglascamata
- name: paologallinaharbur
- name: davidbrota
- name: gsanchezgavier
- name: roobre
name: nri-kube-events
version: 1.9.0
