apiVersion: v1
appVersion: 1.4.0
description: A Helm chart to deploy the New Relic metadata injection webhook.
home: https://hub.docker.com/r/newrelic/k8s-metadata-injection
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
keywords:
- infrastructure
- newrelic
- monitoring
maintainers:
- name: douglascamata
- name: paologallinaharbur
- name: davidbrota
- name: gsanchezgavier
- name: roobre
name: nri-metadata-injection
sources:
- https://github.com/newrelic/k8s-metadata-injection
version: 1.4.3
