{{- range $instance := .Values.instances }}
---
apiVersion: terraform.silvios.me/v1alpha1
kind: StackInstance
metadata:
  name: {{ $instance.name }}
spec:
  stack:
    provider: azurerm
    backend: azurerm
    registry: docker.io
    image: silviosilva/azure-bucket
    version: 0.1.2
  vars:
    name: {{ $instance.name }}
    location: {{ $instance.location }}
    resource_group_name: {{ $instance.resource_group_name }}
  outputs:
    - storage_account_id
    - primary_access_key
    - secondary_access_key
{{- end }}
