apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: clusters.kubernetes.silvios.me
spec:
  compositeTypeRef:
    apiVersion: kubernetes.silvios.me/v1alpha1
    kind: Cluster
  resources:
    - name: overcloud-aks-cluster
      base: 
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: terraform.silvios.me/v1alpha1
              kind: StackInstance
              metadata:
                namespace: default
              spec:
                stack:
                  provider: azurerm
                  backend: azurerm
                  registry: docker.io
                  image: silviosilva/azure-kubernetes-cluster
                  version: 0.3.1
                vars:
                  cluster_name: "wasp-cluster"
                  cluster_location: "eastus2"
                  cluster_version: "1.21.2"
                outputs:
                  - aks_id
                  - aks_kubelet_identity_client_id
                  - kubeconfig

      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.manifest.spec.vars.cluster_name

        - type: FromCompositeFieldPath
          fromFieldPath: spec.region
          toFieldPath: spec.forProvider.manifest.spec.vars.cluster_location

        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.manifest.metadata.name

    - name: overcloud-provider-config-helm
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: ProviderConfig
        spec:
          credentials:
            source: Secret
            secretRef:
              namespace: default
              key: kubeconfig
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name

        - fromFieldPath: metadata.name
          toFieldPath: spec.credentials.secretRef.name

      readinessChecks:
        - type: None

    - name: overcloud-provider-config-kubernetes
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: ProviderConfig
        spec:
          credentials:
            source: Secret
            secretRef:
              namespace: default
              key: kubeconfig
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name

        - fromFieldPath: metadata.name
          toFieldPath: spec.credentials.secretRef.name

      readinessChecks:
        - type: None

    - name: overcloud-terraform-controller
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          name: terraform-controller
          annotations: 
            crossplane.io/external-name: terraform-controller
        spec:
          forProvider:
            chart:
              name: terraform-controller
              repository: https://smsilva.github.io/helm
              version: 0.1.5
            namespace: default
            wait: true
            set: 
              - name: secrets.azurerm.data.clientId
                valueFrom: 
                  secretKeyRef: 
                    name: azurerm-credentials
                    namespace: default
                    key: ARM_CLIENT_ID

              - name: secrets.azurerm.data.clientSecret
                valueFrom: 
                  secretKeyRef: 
                    name: azurerm-credentials
                    namespace: default
                    key: ARM_CLIENT_SECRET

              - name: secrets.azurerm.data.tenantId
                valueFrom: 
                  secretKeyRef: 
                    name: azurerm-credentials
                    namespace: default
                    key: ARM_TENANT_ID

              - name: secrets.azurerm.data.keyVaultName
                valueFrom: 
                  secretKeyRef: 
                    name: azurerm-credentials
                    namespace: default
                    key: ARM_KEYVAULT_NAME
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: spec.providerConfigRef.name

    - name: overcloud-crossplane
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          name: crossplane
          annotations: 
            crossplane.io/external-name: crossplane
        spec:
          forProvider:
            chart:
              name: crossplane
              repository: https://charts.crossplane.io/stable
              version: 1.5.1
            namespace: crossplane-system
            wait: true
            skipCreateNamespace: false

      patches:
        - fromFieldPath: metadata.name
          toFieldPath: spec.providerConfigRef.name

    - name: overcloud-argocd
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          name: argocd
          annotations: 
            crossplane.io/external-name: argocd
        spec:
          forProvider:
            chart:
              name: argo-cd
              repository: https://argoproj.github.io/argo-helm
              version: 3.13.0
            namespace: argocd
            wait: true
            values:
              server:
                service:
                  type: ClusterIP
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: spec.providerConfigRef.name

    - name: overcloud-argocd-application
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: argoproj.io/v1alpha1
              kind: Application
              metadata:
                name: bootstrap
                namespace: argocd
                annotations: 
                  crossplane.io/external-name: argocd-bootstrap
                finalizers:
                  - resources-finalizer.argocd.argoproj.io
              spec:
                project: default
                destination:
                  namespace: default
                  name: in-cluster
                source:
                  repoURL: https://github.com/smsilva/argocd.git
                  targetRevision: wasp
                  path: charts/overcloud
                syncPolicy:
                  automated:
                    prune: true
                    selfHeal: true

      patches:
        - fromFieldPath: metadata.name
          toFieldPath: spec.providerConfigRef.name
