apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: clusters.kubernetes.silvios.me
spec:
  compositeTypeRef:
    apiVersion: kubernetes.silvios.me/v1alpha1
    kind: Cluster
  resources:
    - base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: terraform.silvios.me/v1alpha1
              kind: StackInstance
              metadata:
                namespace: default
              spec:
                stack:
                  provider: azurerm
                  backend: azurerm
                  registry: docker.io
                  image: silviosilva/azure-undercloud-cluster
                  version: 0.3.0
                vars:
                  cluster_location: eastus2
                  cluster_version: "1.21.2"
                outputs:
                  - aks_id
                  - aks_kubelet_identity_client_id
                  - kubeconfig

      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.manifest.metadata.name

        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.manifest.spec.vars.cluster_name

        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.manifest.metadata.name
          transforms:
            - type: string
              string:
                fmt: "azure-k8s-cluster-%s"

    - base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: ProviderConfig
        spec:
          credentials:
            source: Secret
            secretRef:
              namespace: default
              key: kubeconfig
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name

        - fromFieldPath: metadata.name
          toFieldPath: spec.credentials.secretRef.name
          transforms:
            - type: string
              string:
                fmt: "azure-k8s-cluster-%s"
      readinessChecks:
        - type: None

    - base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          name: argocd
        spec:
          forProvider:
            chart:
              name: argo-cd
              repository: https://argoproj.github.io/argo-helm
              version: 3.13.0
            namespace: argocd
            wait: true
            values:
              server:
                service:
                  type: ClusterIP
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name

        - fromFieldPath: metadata.name
          toFieldPath: spec.providerConfigRef.name

    - base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: Secret
              metadata:
                name: azurerm-credentials
              type: Opaque

    - base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: Secret
              metadata:
                name: azurerm-credentials
              type: Opaque
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: spec.providerConfigRef.name
