apiVersion: v1
appVersion: 1.4.6
description: A Helm chart to deploy New Relic Kubernetes Logging as a DaemonSet
home: https://github.com/newrelic/kubernetes-logging
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
keywords:
- logging
- newrelic
maintainers:
- email: logging-team@newrelic.com
  name: jsubirat
- name: tejunior
- name: jodstrcil
- name: edmocosta
name: newrelic-logging
version: 1.4.8
