---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{if .Values.customAnnotations}}{{range $element := split "," .Values.customAnnotations -}}
    {{ $kv := split "=" $element -}}
    {{if eq (len $kv) 2 -}}
    {{ $kv._0 }}: "{{ $kv._1 }}"
    {{- end}}
    {{end}}{{end}}
  labels:
    {{if .Values.customLabels}}{{range $element := split "," .Values.customLabels -}}
    {{ $kv := split "=" $element -}}
    {{if eq (len $kv) 2 -}}
    {{ $kv._0 }}: "{{ $kv._1 }}"
    {{- end}}
    {{end}}{{end}}
    app: pl-monitoring
  name: nats-operator
  namespace: {{ if .Release.Namespace }}{{ .Release.Namespace }}{{ else }}pl{{ end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{if .Values.customAnnotations}}{{range $element := split "," .Values.customAnnotations -}}
    {{ $kv := split "=" $element -}}
    {{if eq (len $kv) 2 -}}
    {{ $kv._0 }}: "{{ $kv._1 }}"
    {{- end}}
    {{end}}{{end}}
  labels:
    {{if .Values.customLabels}}{{range $element := split "," .Values.customLabels -}}
    {{ $kv := split "=" $element -}}
    {{if eq (len $kv) 2 -}}
    {{ $kv._0 }}: "{{ $kv._1 }}"
    {{- end}}
    {{end}}{{end}}
    app: pl-monitoring
  name: nats-server
  namespace: {{ if .Release.Namespace }}{{ .Release.Namespace }}{{ else }}pl{{ end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    {{if .Values.customAnnotations}}{{range $element := split "," .Values.customAnnotations -}}
    {{ $kv := split "=" $element -}}
    {{if eq (len $kv) 2 -}}
    {{ $kv._0 }}: "{{ $kv._1 }}"
    {{- end}}
    {{end}}{{end}}
  labels:
    {{if .Values.customLabels}}{{range $element := split "," .Values.customLabels -}}
    {{ $kv := split "=" $element -}}
    {{if eq (len $kv) 2 -}}
    {{ $kv._0 }}: "{{ $kv._1 }}"
    {{- end}}
    {{end}}{{end}}
    app: pl-monitoring
  name: pl:nats-operator
  namespace: {{ if .Release.Namespace }}{{ .Release.Namespace }}{{ else }}pl{{ end }}
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - nats.io
  resources:
  - natsclusters
  - natsserviceroles
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - pods
  - pods/exec
  - pods/log
  - services
  - serviceaccounts
  - serviceaccounts/token
  - endpoints
  - events
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    {{if .Values.customAnnotations}}{{range $element := split "," .Values.customAnnotations -}}
    {{ $kv := split "=" $element -}}
    {{if eq (len $kv) 2 -}}
    {{ $kv._0 }}: "{{ $kv._1 }}"
    {{- end}}
    {{end}}{{end}}
  labels:
    {{if .Values.customLabels}}{{range $element := split "," .Values.customLabels -}}
    {{ $kv := split "=" $element -}}
    {{if eq (len $kv) 2 -}}
    {{ $kv._0 }}: "{{ $kv._1 }}"
    {{- end}}
    {{end}}{{end}}
    app: pl-monitoring
  name: pl:nats-server
  namespace: {{ if .Release.Namespace }}{{ .Release.Namespace }}{{ else }}pl{{ end }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    {{if .Values.customAnnotations}}{{range $element := split "," .Values.customAnnotations -}}
    {{ $kv := split "=" $element -}}
    {{if eq (len $kv) 2 -}}
    {{ $kv._0 }}: "{{ $kv._1 }}"
    {{- end}}
    {{end}}{{end}}
  labels:
    {{if .Values.customLabels}}{{range $element := split "," .Values.customLabels -}}
    {{ $kv := split "=" $element -}}
    {{if eq (len $kv) 2 -}}
    {{ $kv._0 }}: "{{ $kv._1 }}"
    {{- end}}
    {{end}}{{end}}
    app: pl-monitoring
  name: pl:nats-operator-binding
  namespace: {{ if .Release.Namespace }}{{ .Release.Namespace }}{{ else }}pl{{ end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pl:nats-operator
subjects:
- kind: ServiceAccount
  name: nats-operator
  namespace: {{ if .Release.Namespace }}{{ .Release.Namespace }}{{ else }}pl{{ end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    {{if .Values.customAnnotations}}{{range $element := split "," .Values.customAnnotations -}}
    {{ $kv := split "=" $element -}}
    {{if eq (len $kv) 2 -}}
    {{ $kv._0 }}: "{{ $kv._1 }}"
    {{- end}}
    {{end}}{{end}}
  labels:
    {{if .Values.customLabels}}{{range $element := split "," .Values.customLabels -}}
    {{ $kv := split "=" $element -}}
    {{if eq (len $kv) 2 -}}
    {{ $kv._0 }}: "{{ $kv._1 }}"
    {{- end}}
    {{end}}{{end}}
    app: pl-monitoring
  name: pl:nats-server-binding
  namespace: {{ if .Release.Namespace }}{{ .Release.Namespace }}{{ else }}pl{{ end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pl:nats-server
subjects:
- kind: ServiceAccount
  name: nats-server
  namespace: {{ if .Release.Namespace }}{{ .Release.Namespace }}{{ else }}pl{{ end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{if .Values.customAnnotations}}{{range $element := split "," .Values.customAnnotations -}}
    {{ $kv := split "=" $element -}}
    {{if eq (len $kv) 2 -}}
    {{ $kv._0 }}: "{{ $kv._1 }}"
    {{- end}}
    {{end}}{{end}}
  labels:
    {{if .Values.customLabels}}{{range $element := split "," .Values.customLabels -}}
    {{ $kv := split "=" $element -}}
    {{if eq (len $kv) 2 -}}
    {{ $kv._0 }}: "{{ $kv._1 }}"
    {{- end}}
    {{end}}{{end}}
    app: pl-monitoring
  name: nats-operator
  namespace: {{ if .Release.Namespace }}{{ .Release.Namespace }}{{ else }}pl{{ end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pl-monitoring
      name: nats-operator
  template:
    metadata:
      annotations:
        {{if .Values.customAnnotations}}{{range $element := split "," .Values.customAnnotations -}}
        {{ $kv := split "=" $element -}}
        {{if eq (len $kv) 2 -}}
        {{ $kv._0 }}: "{{ $kv._1 }}"
        {{- end}}
        {{end}}{{end}}
      labels:
        {{if .Values.customLabels}}{{range $element := split "," .Values.customLabels -}}
        {{ $kv := split "=" $element -}}
        {{if eq (len $kv) 2 -}}
        {{ $kv._0 }}: "{{ $kv._1 }}"
        {{- end}}
        {{end}}{{end}}
        app: pl-monitoring
        name: nats-operator
        plane: control
    spec:
      containers:
      - args:
        - nats-operator
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: connecteverything/nats-operator:0.5.0-v1alpha2
        imagePullPolicy: IfNotPresent
        name: nats-operator
        ports:
        - containerPort: 8080
          name: readyz
        readinessProbe:
          httpGet:
            path: /readyz
            port: readyz
          initialDelaySeconds: 15
          timeoutSeconds: 3
      serviceAccountName: nats-operator
---
apiVersion: nats.io/v1alpha2
kind: NatsCluster
metadata:
  annotations:
    {{if .Values.customAnnotations}}{{range $element := split "," .Values.customAnnotations -}}
    {{ $kv := split "=" $element -}}
    {{if eq (len $kv) 2 -}}
    {{ $kv._0 }}: "{{ $kv._1 }}"
    {{- end}}
    {{end}}{{end}}
  labels:
    {{if .Values.customLabels}}{{range $element := split "," .Values.customLabels -}}
    {{ $kv := split "=" $element -}}
    {{if eq (len $kv) 2 -}}
    {{ $kv._0 }}: "{{ $kv._1 }}"
    {{- end}}
    {{end}}{{end}}
    app: pl-monitoring
  name: pl-nats
  namespace: {{ if .Release.Namespace }}{{ .Release.Namespace }}{{ else }}pl{{ end }}
spec:
  size: 1
  tls:
    serverSecret: service-tls-certs
    serverSecretCAFileName: ca.crt
    serverSecretCertFileName: server.crt
    serverSecretKeyFileName: server.key
  version: 1.3.0
