apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: storage.silvios.me
spec:
  group: storage.silvios.me
  names:
    kind: Bucket
    listKind: BucketList
    plural: buckets
    shortNames: []
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                region:
                  type: string
              required:
                - region
