---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: buckets.azure.storage.silvios.me
  labels:
    provider: kubernetes
spec:
  compositeTypeRef:
    apiVersion: azure.storage.silvios.me/v1alpha1
    kind: Bucket
  resources:
    - base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: terraform.silvios.me/v1alpha1
              kind: StackInstance
              metadata:
                namespace: default
              spec:
                stack:
                  provider: azurerm
                  backend: azurerm
                  registry: docker.io
                  image: silviosilva/azure-bucket
                  version: 0.1.3
                vars:
                  name: generic-bucket-name
                  location: generic-bucket-location
                outputs:
                  - storage_account_id
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.manifest.metadata.name
          transforms:
            - type: string
              string:
                fmt: "azure-bucket-%s"

        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.manifest.spec.vars.name

        - type: FromCompositeFieldPath
          fromFieldPath: spec.location
          toFieldPath: spec.forProvider.manifest.spec.vars.location
